Add IDisposable Implementation To MemoryStreamLogger
MikeK93/MentoringProgram pull request #2
Opened 2017-05-20 13:50 UTC by MikeK93

2017-05-22 08:31 UTC, smallnonsense requested changes

2017-05-22 08:31 UTC, smallnonsense commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/MemoryStreamLogger.cs
> +            GC.SuppressFinalize(this);
а для чого це тут? чи може ще чогось не вистачає щоб це мало сенс?

2017-05-22 08:31 UTC, smallnonsense commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/MemoryStreamLogger.cs
> +            streamWriter?.Dispose();
1) за яких умов streamWriter буде null?
2) що станеться якщо 2 рази викликати Dispose()?

2017-05-22 08:31 UTC, smallnonsense commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/MemoryStreamLogger.cs
>          private StreamWriter streamWriter;
а навіщо два поля?

2017-05-22 08:31 UTC, smallnonsense commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/MemoryStreamLogger.cs
> +            memoryStream = new FileStream(@"\log.txt", FileMode.OpenOrCreate | FileMode.Append);
на production сумнівно що буде прив"язка до конкретного файла і навіть потоку даних.

2017-05-22 08:31 UTC, smallnonsense commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/Program.cs
>                  WriteLog("Interation number #" + i);
скільки логерів потрібно щоб залогувати 10к повідомлень?

2017-05-22 10:20 UTC, MikeK93 commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/MemoryStreamLogger.cs
> +            streamWriter?.Dispose();
1. никогда, разве что кто-то засетит его в null
2. ничего, а вот если вызвать метод Log после Dispose то будет ексепшн

2017-05-22 10:24 UTC, MikeK93 commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/MemoryStreamLogger.cs
> +            GC.SuppressFinalize(this);
> а для чого це тут?

инструкция которая говорит о том что процесс финализации для текущего обьекта не нужен



> чи може ще чогось не вистачає щоб це мало сенс?


реализация Finalize. по дефолту все обьекты не finalizable

2017-05-22 10:44 UTC, smallnonsense commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/MemoryStreamLogger.cs
> +            memoryStream = new FileStream(@"\log.txt", FileMode.OpenOrCreate | FileMode.Append);
Ігор сказав, DI можна тут не зачіпати. Повернемось до цього в інших темах

2017-05-22 10:48 UTC, smallnonsense commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/MemoryStreamLogger.cs
> +            streamWriter?.Dispose();
ну я питання задаю лише наводящі, зазвичай :)
1) якщо ніколи, то навіщо елвіс оператор?!
2) спробуй викликати його в Program.cs після using(...){...} щоб зняти всі питання

взагалі в теорії повинен був бути описаний стандартний приклад реалізації. краще спробувати його щоб зрозуміти всі підводні камені.

2017-05-22 10:52 UTC, smallnonsense commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/MemoryStreamLogger.cs
> +            GC.SuppressFinalize(this);
> реализация Finalize. по дефолту все обьекты не finalizable
так а цей логгер має фіналізацію?

2017-05-22 11:11 UTC, MikeK93 commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/MemoryStreamLogger.cs
> +            streamWriter?.Dispose();
1. при тестировании делал null, и не удалил элвис оператор, сорри

да, я читал на [msdn](https://msdn.microsoft.com/en-us/library/b1yfkh5e(v=vs.110).aspx?f=255&mspperror=-2147217396#Anchor_0). Булевый параметр в том методе (`Dispose(bool disposing){...}`) используеться для индикации того dispose ли это или нет, а так как нету другого варианта в этом логере, то есть ли смысл для создания этого метода с таким параметром или только в том случае когда есть иерархия классов?

2017-05-22 11:16 UTC, MikeK93 commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/MemoryStreamLogger.cs
> +            streamWriter?.Dispose();
> cпробуй викликати його в Program.cs в using(...){...; logger.Dispose();} щоб зняти всі питання

Вызвал это и нормально все прошло.
```C#
using (var logger = new MemoryStreamLogger())
{
    logger.Log("Ha");
    logger.Dispose();
}
```

А вот этот код упал, что есть ожидаемым поведением.
```C#
using (var logger = new MemoryStreamLogger())
{
    logger.Log("Ha");
    logger.Dispose();
    logger.Log(":(");
}
```

2017-05-22 11:17 UTC, MikeK93 commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/MemoryStreamLogger.cs
> +            GC.SuppressFinalize(this);
нет, так как у него нету финализатора

2017-05-22 11:19 UTC, MikeK93 commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/Program.cs
>                  WriteLog("Interation number #" + i);
вообще можно обойтись и одним, но тут на каждой итерации создаеться свой логер

2017-05-22 13:15 UTC, smallnonsense commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/MemoryStreamLogger.cs
> +            streamWriter?.Dispose();
тут, схоже, почастило, що StreamWriter безбечна обгортка. Можливі помилки типу ObjectDisposedException якщо стрім приходить зовні. ну нехай поки так.

Прочитай уважніше статтю, а особливо про
1) рекомендації про кидання виключень в відкритих членах та вчасності у Dispose
2) Finalizable Types

Якщо клас не закритий, то можливе його розширення і щоб не виникло проблем у нащадка - робиться стандартне Dispose API що дозволяє з коротко розшрити все що треба і нічого не поламати. Але це ж використовується і при наявності фіналізатора.

2017-05-22 13:22 UTC, smallnonsense commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/MemoryStreamLogger.cs
> +            GC.SuppressFinalize(this);
тоді йому не потрібна очистка з черги фіналізатора. читай коментар вище я там відповів на це питання.

2017-05-22 13:24 UTC, smallnonsense commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/Program.cs
>                  WriteLog("Interation number #" + i);
а в чому ідея, навіщо так робити?! я просто не зрозумів. Це типу перфоманс тест такий чи що?

2017-05-22 13:28 UTC, MikeK93 commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/Program.cs
>                  WriteLog("Interation number #" + i);
идея в том что если не реализовать IDisposable то приложение вообще не будет работать

2017-05-22 13:34 UTC, MikeK93 commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/MemoryStreamLogger.cs
> +            streamWriter?.Dispose();
Ошибка типа ObjectDisposedException будет если использовать logger после вызова Dispose.
Но в продакшине, разве нужно Dispose API делать в случае когда нету намерений делать иерархию или не понятно будет ли она?

2017-05-22 13:39 UTC, MikeK93 commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/MemoryStreamLogger.cs
> +            streamWriter?.Dispose();
И нужно ли кидать ексепш в этом случае т.к. streamWriter уже кидает если он был очищен?

2017-05-23 11:38 UTC, smallnonsense commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/MemoryStreamLogger.cs
> +            streamWriter?.Dispose();
вcі помилки що кідають внутрішні об'єкти це можливо розкриття внутрішньої реалізації. тому ту поведінку яку ми можемо передбачити краще оброблювати окремо. 
Це у нас немає намірів створювати нащадків, але над кодом у "продакшені" працюватимумо не лише ми. а ще якщо ця логіка потрапить в якусь пакет, то нас всі користувачі будуть згадувати не злим тихим словом. 
Завжди треба намагатись писати код за який потім щоб не було соромно.

2017-05-23 11:40 UTC, smallnonsense commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/Program.cs
>                  WriteLog("Interation number #" + i);
а чому перестане працювати і що можна зробити щоб не переставало? Окрім поточної реалізації звісно.

2017-05-23 12:52 UTC, MikeK93 commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/Program.cs
>                  WriteLog("Interation number #" + i);
из-за того что на каждой итерации создавался логгер который захватывал ресурс и по выходу из метода не релизил его. можно было бы внутри логера в методе Log открывать файл и закрывать

2017-05-23 15:43 UTC, smallnonsense commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/Program.cs
>                  WriteLog("Interation number #" + i);
Непоганий варіант, але швидкодія впаде та і IDisposaple вже зайвий. Подумай до завтра :)

2017-05-24 09:38 UTC, MikeK93 commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/Program.cs
>                  WriteLog("Interation number #" + i);
можно обернуть for-loop using'ом в котором будет создаваться target stream и пробрасывать его во WriteLog метод, таким образом логгеру все равно от куда взялся stream, глявное что бы можно было туда писать.

2017-05-24 10:52 UTC, smallnonsense commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/Program.cs
>                  WriteLog("Interation number #" + i);
Оце якраз більш розумний підхід. Взагалі цей метод зайвий, бо нічого толком не дає.

2017-05-24 11:00 UTC, MikeK93 commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/Program.cs
>                  WriteLog("Interation number #" + i);
я просто подумал что нужно решить проблему как раз с учетем этого метода. Но если нужно я перепишу.

2017-05-24 13:33 UTC, MikeK93 commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/MemoryStreamLogger.cs
> +            GC.SuppressFinalize(this);
got it

2017-05-24 13:35 UTC, MikeK93 commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/MemoryStreamLogger.cs
> +            streamWriter?.Dispose();
пытаюсь писать код что бы за него было не стыдно, а получаеться как всегда) но буду работать над этим

2017-05-24 13:35 UTC, MikeK93 commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/MemoryStreamLogger.cs
>          private StreamWriter streamWriter;
уже одно

2017-05-26 14:15 UTC, smallnonsense commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/Program.cs
>                  WriteLog("Interation number #" + i);
досі бачу цю логіку

2017-06-01 09:17 UTC, smallnonsense requested changes

2017-06-01 09:17 UTC, smallnonsense commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/Program.cs
> +            void WriteLog(Stream to, string text)
цього методу можна взагалі позбутись. він лише заплутує логіку

2017-06-01 09:17 UTC, smallnonsense commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/Program.cs
> +            var t = new Stopwatch();
а навіщо скрізь використовується один і тойже ж екземпляр Stopwatch? В даному випадку кожен може мати свого.
гарною практикою є використання примітивів там де вони створюється, а передаються, зазвичай, лише те що впливає на логіку в методі.
запис і виведення часу запуску можна ізолювати в окремому методі, що отримує Action делегат, щоб воно не плуталось під ногами

2017-06-01 09:17 UTC, smallnonsense commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/Program.cs
> +            Console.WriteLine($"{t.Elapsed}");
і які результати вийшли? що скільки часу зайняло?

2017-06-01 20:34 UTC, MikeK93 commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/Program.cs
> +            var t = new Stopwatch();
ok, испарвлю

2017-06-01 20:34 UTC, MikeK93 commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/Program.cs
> +            void WriteLog(Stream to, string text)
просто хотел хоть где-то заюзать фичи C# 7 :)

2017-06-01 21:01 UTC, MikeK93 commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/Program.cs
> +            Console.WriteLine($"{t.Elapsed}");
DisposingLoggerAndTargetInsideLoop took 00:00:47.1641417.
DisposingLoggerAndTarget took 00:00:00.0208822.
DisposingOnlyTarget took 00:00:01.1350258.

2017-06-07 13:56 UTC, smallnonsense requested changes

2017-06-07 13:56 UTC, smallnonsense commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/Program.cs
> +                        WriteLog(file, $"Interation number #{i}");
what is the point to have nested method? correct me if I'm wrong but we have been talking regarding that, haven't we?

2017-06-07 13:56 UTC, smallnonsense commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/Program.cs
> +            TimeLogger(nameof(DisposingLoggerAndTargetInsideLoop), () =>
it looks a bit strange. why not following?
TimeLogger(DisposingLoggerAndTargetInsideLoop);
...
TimeLogger(Action action)
{
..
    Console.WriteLine(action.Method.Name);
..
 }

2017-06-07 14:00 UTC, smallnonsense commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/Program.cs
> +            using (var file = File.CreateText($"{actionName}-log.txt"))
why tracking metrics into file instead of console? is it for the history reason?

2017-06-07 14:05 UTC, smallnonsense commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/Program.cs
> +            void WriteLog(Stream to, string text)
ти ще просто не ловив поломані білди через такі "приколи" :)
це одна з самих безтолкових нововедень з дуже обмеженим використанням.

2017-06-07 14:06 UTC, smallnonsense commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/Program.cs
> +            Console.WriteLine($"{t.Elapsed}");
як неочікувано.

2017-06-07 20:42 UTC, MikeK93 commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/Program.cs
> +            void WriteLog(Stream to, string text)
ловил уже :)
и да, эта фича не понятно где будет юзабельной.

2017-06-07 20:47 UTC, MikeK93 commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/Program.cs
> +            TimeLogger(nameof(DisposingLoggerAndTargetInsideLoop), () =>
Indeed, looks better. Thanks

2017-06-07 20:49 UTC, MikeK93 commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/Program.cs
> +                        WriteLog(file, $"Interation number #{i}");
removed

2017-06-07 20:53 UTC, MikeK93 commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/Program.cs
> +            using (var file = File.CreateText($"{actionName}-log.txt"))
it's done so that you can see the result without opening the file.
plus I believe its already writing metrics to the file with the lines below:
```C#
using (var file = File.CreateText($"{actionName}-log.txt"))
{
    var t = new Stopwatch();
    t.Start();

    action();

    t.Stop();
    string logMessage = $"{actionName} took {t.Elapsed}.";
    Console.WriteLine(logMessage); // <- here to console
    file.Write(logMessage); // <- here to file 
}
```

2017-06-08 08:35 UTC, smallnonsense commented on practice/tasks/IDisposable/IDisposableImplementation/IDisposableImplementation/Program.cs
> +            using (var file = File.CreateText($"{actionName}-log.txt"))
Ah, both file and console logging is available. that's OK then

2017-06-08 08:36 UTC, smallnonsense approved these changes

2017-06-12 12:22 UTC, merged